contact_links:
  - name: Join us on Kubernetes slack
    url: https://slack.k8s.io/
    about: |
      #olm-dev - Discussions related to OLM Development\n
      #kubernetes-operators - Discussions related to the Operator pattern of Kubernetes API extension.
